NameFood = input("what's your food? ")
NamePlant = input("what's your type of plant? ")
NameCooking = input("what's the method of cooking? ")
BurnedFood = input("what word describes burned food? ")
DiyItem = input("what's a DIY item? ")
print(NameCooking, NameFood, "with", BurnedFood, NamePlant, "on a bed of", DiyItem)